import * as XLSX from 'xlsx';
import type { Intern } from '@/types/intern';

const COL_MAP: Record<string, keyof Intern> = {
  'Timestamp': 'timestamp',
  'First Name': 'firstName',
  'Last Name': 'lastName',
  'What is your phone number?': 'phone',
  "What is your parent/guardian's phone number?": 'parentPhone',
  'Date of Birth': 'dob',
  'Which CMSD school do you attend?': 'school',
  'What grade are you currently enrolled in?': 'grade',
  'Would you be interested in working for the Cleveland Clinic': 'clevelandClinic',
  'Would you be interested in an internship in Construction Management?': 'constructionMgmt',
  'Would you be interested in an internship in Biomedical Science and Engineering?': 'biomedical',
  'Would you be interested in an internship in Environmental Sustainability: Environmental Justice?': 'envJustice',
  'Would you be interested in an internship in Environmental Sustainability: Climate Adaptation and Resilience?': 'envClimate',
  'Would you be interested in an internship in Environmental Sustainability: Field Science and Data Analytics?': 'envFieldScience',
  "Are you interested in an internship with Cleveland State University's IERS Center": 'iersCenter',
  "Are you interested in an internship with MAGNET's Summer Manufacturing Academy?": 'magnetManufacturing',
  'Are you interested in an education-oriented internship': 'educationInternship',
  'Are you interested in an internship in healthcare-related career fields?': 'healthcare',
  'Are you interested in an internship where you would be designing video games': 'videoGames',
  'Have you ever taken a Computer Science or IT course?': 'csCourseTaken',
  "Do you have specific interests that weren't listed above?": 'specificInterests',
  'What additional questions do you have?': 'additionalQuestions',
};

function findColumn(headers: string[], search: string): number {
  return headers.findIndex(h => h && h.toLowerCase().includes(search.toLowerCase()));
}

function getVal(row: any[], headers: string[], search: string): string {
  const idx = findColumn(headers, search);
  return idx >= 0 ? String(row[idx] ?? '').trim() : '';
}

export function parseExcelFile(data: ArrayBuffer): Intern[] {
  const workbook = XLSX.read(data, { type: 'array' });
  
  console.log('=== EXCEL PARSE DEBUG ===');
  console.log('Sheet names:', workbook.SheetNames);
  
  let headers: string[] = [];
  let dataRows: any[][] = [];
  
  for (const sheetName of workbook.SheetNames) {
    const sheet = workbook.Sheets[sheetName];
    const rows: any[][] = XLSX.utils.sheet_to_json(sheet, { header: 1 });
    console.log(`\n=== Sheet "${sheetName}": ${rows.length} rows ===`);
    if (rows.length < 2) continue;
    
    // Log first 10 rows for debugging, but show more detail
    for (let i = 0; i < Math.min(rows.length, 10); i++) {
      const row = rows[i] || [];
      const cells = row.map((c: any) => String(c ?? ''));
      if (cells.some(c => c.length > 0)) {
        console.log(`  Row ${i}: [${cells.map((c, idx) => `${idx}: "${c}"`).filter((_, idx) => cells[idx]).join(', ')}]`);
      }
    }
    
    // Find header row by scanning up to 30 rows
    let headerIdx = -1;
    for (let i = 0; i < Math.min(rows.length, 30); i++) {
      const cells = (rows[i] || []).map((c: any) => String(c ?? '').toLowerCase().trim());
      const nonEmpty = cells.filter(c => c.length > 0);
      if (nonEmpty.length < 2) continue;
      
      const rowStr = cells.join(' ');
      
      // Check for common header patterns - very broad matching
      const hasName = rowStr.includes('first name') || rowStr.includes('last name') || rowStr.includes('full name') || rowStr.includes('student name') || rowStr.includes('youth name') || rowStr.includes('participant');
      const hasContact = rowStr.includes('email') || rowStr.includes('phone') || rowStr.includes('contact');
      const hasSchool = rowStr.includes('grade') || rowStr.includes('school') || rowStr.includes('district');
      const hasStatus = rowStr.includes('status') || rowStr.includes('program') || rowStr.includes('site') || rowStr.includes('worksite') || rowStr.includes('placement');
      const hasGeneric = rowStr.includes('name') || rowStr.includes('first') || rowStr.includes('last');
      
      if (
        hasName ||
        (hasGeneric && (hasContact || hasSchool || hasStatus)) ||
        (hasContact && hasSchool) ||
        // Broad fallback: row with 3+ short header-like cells that look like column titles
        (nonEmpty.length >= 3 && nonEmpty.every(c => c.length < 50) && !rowStr.includes('recommended') && !rowStr.includes('generated by') && !rowStr.includes('as of'))
      ) {
        headerIdx = i;
        console.log(`  >>> HEADER ROW FOUND at index ${i}:`, JSON.stringify(cells.filter(c => c)));
        break;
      }
    }
    
    if (headerIdx >= 0) {
      headers = rows[headerIdx].map((h: any) => String(h ?? ''));
      dataRows = rows.slice(headerIdx + 1);
      console.log(`  Using ${dataRows.length} data rows after header`);
      break;
    } else {
      console.log('  No header row detected on this sheet');
    }
  }
  
  // Fallback: if no headers found, use first non-empty row with 3+ cells
  if (headers.length === 0) {
    console.log('=== FALLBACK: scanning all sheets for any usable row ===');
    for (const sheetName of workbook.SheetNames) {
      const sheet = workbook.Sheets[sheetName];
      const rows: any[][] = XLSX.utils.sheet_to_json(sheet, { header: 1 });
      for (let i = 0; i < Math.min(rows.length, 30); i++) {
        const cells = (rows[i] || []).map((c: any) => String(c ?? '').trim());
        const nonEmpty = cells.filter(c => c.length > 0);
        if (nonEmpty.length >= 3) {
          headers = cells;
          dataRows = rows.slice(i + 1);
          console.log(`  Fallback header from "${sheetName}" row ${i}:`, JSON.stringify(nonEmpty));
          break;
        }
      }
      if (headers.length > 0) break;
    }
  }
  
  if (headers.length === 0 || dataRows.length === 0) {
    console.log('NO DATA FOUND. Total sheets:', workbook.SheetNames.length);
    return [];
  }
  
  const emailIdx1 = 1; // "Email Address" (submission)
  const emailIdx2 = findColumn(headers, 'student\'s email') >= 0 
    ? findColumn(headers, 'student\'s email')
    : findColumn(headers, 'This should be the student');

  // Detect if we have separate first/last name columns or a combined "Contact"/"Name" column
  const hasFirstName = findColumn(headers, 'First Name') >= 0;
  const hasLastName = findColumn(headers, 'Last Name') >= 0;
  const contactIdx = findColumn(headers, 'Contact') >= 0 ? findColumn(headers, 'Contact')
    : findColumn(headers, 'Full Name') >= 0 ? findColumn(headers, 'Full Name')
    : findColumn(headers, 'Student Name') >= 0 ? findColumn(headers, 'Student Name')
    : findColumn(headers, 'Youth Name') >= 0 ? findColumn(headers, 'Youth Name')
    : findColumn(headers, 'Participant') >= 0 ? findColumn(headers, 'Participant')
    : findColumn(headers, 'Name') >= 0 ? findColumn(headers, 'Name')
    : -1;

  console.log('Name detection:', { 
    hasFirstName, 
    hasLastName, 
    contactIdx,
    contactHeader: contactIdx >= 0 ? headers[contactIdx] : 'none',
    allHeaders: headers.map((h, i) => `${i}: "${h}"`).filter((_, i) => headers[i])
  });

  const interns: Intern[] = [];
  let skippedRows = 0;
  let emptyNameRows = 0;
  let shortRows = 0;
  
  console.log(`\n=== Processing ${dataRows.length} data rows ===`);
  
  for (let i = 0; i < dataRows.length; i++) {
    const row = dataRows[i];
    if (!row) {
      console.log(`Row ${i} - Row is null/undefined, skipping`);
      skippedRows++;
      continue;
    }
    
    // More lenient: allow rows with just 1 column if it has content
    const nonEmptyCells = row.filter((cell: any) => String(cell ?? '').trim().length > 0);
    if (nonEmptyCells.length === 0) {
      console.log(`Row ${i} - Row is completely empty, skipping`);
      shortRows++;
      continue;
    }
    
    let firstName = '';
    let lastName = '';

    if (hasFirstName || hasLastName) {
      firstName = getVal(row, headers, 'First Name');
      lastName = getVal(row, headers, 'Last Name');
      console.log(`Row ${i} - Using separate name columns: "${firstName}" "${lastName}"`);
    } else if (contactIdx >= 0) {
      const fullName = String(row[contactIdx] ?? '').trim();
      console.log(`Row ${i} - Full name from index ${contactIdx}: "${fullName}"`);
      if (fullName) {
        const parts = fullName.split(/\s+/);
        firstName = parts[0] || '';
        lastName = parts.slice(1).join(' ') || '';
        console.log(`Row ${i} - Split into: "${firstName}" "${lastName}"`);
      }
    } else {
      console.log(`Row ${i} - No name columns detected, trying fallback methods`);
      // Fallback: try to find name in any column
      for (let colIdx = 0; colIdx < Math.min(row.length, 10); colIdx++) {
        const cellValue = String(row[colIdx] ?? '').trim();
        if (cellValue && cellValue.length > 2 && cellValue.includes(' ')) {
          const parts = cellValue.split(/\s+/);
          if (parts.length >= 2 && parts[0].length > 1 && parts[1].length > 1) {
            firstName = parts[0];
            lastName = parts.slice(1).join(' ');
            console.log(`Row ${i} - Found name in column ${colIdx}: "${firstName}" "${lastName}"`);
            break;
          }
        }
      }
    }

    // More lenient: allow rows with only first name or only last name
    if (!firstName && !lastName) {
      console.log(`Row ${i} - No names found anywhere, skipping row. Available data:`, row.slice(0, 5).map(String));
      emptyNameRows++;
      continue;
    }

    const programsStr = getVal(row, headers, 'Have you participated in any of the following');
    const itStr = getVal(row, headers, 'What areas of IT Interest');
    const otherSchoolStr = getVal(row, headers, 'If you do not attend a CMSD');
    
    const intern: Intern = {
      id: `intern-${i}-${Date.now()}`,
      timestamp: getVal(row, headers, 'Timestamp'),
      emailSubmission: String(row[emailIdx1] ?? '').trim(),
      firstName,
      lastName,
      phone: getVal(row, headers, 'What is your phone number'),
      parentPhone: getVal(row, headers, "parent/guardian's phone"),
      dob: getVal(row, headers, 'Date of Birth'),
      studentEmail: emailIdx2 >= 0 ? String(row[emailIdx2] ?? '').trim() : '',
      school: getVal(row, headers, 'Which CMSD school'),
      otherSchool: otherSchoolStr,
      grade: getVal(row, headers, 'What grade are you currently'),
      programs: programsStr ? programsStr.split(',').map(s => s.trim()).filter(Boolean) : [],
      itInterests: itStr ? itStr.split(',').map(s => s.trim()).filter(Boolean) : [],
      clevelandClinic: getVal(row, headers, 'Cleveland Clinic'),
      constructionMgmt: getVal(row, headers, 'Construction Management'),
      biomedical: getVal(row, headers, 'Biomedical Science'),
      envJustice: getVal(row, headers, 'Environmental Justice'),
      envClimate: getVal(row, headers, 'Climate Adaptation'),
      envFieldScience: getVal(row, headers, 'Field Science'),
      iersCenter: getVal(row, headers, 'IERS Center'),
      magnetManufacturing: getVal(row, headers, "MAGNET"),
      educationInternship: getVal(row, headers, 'education-oriented'),
      healthcare: getVal(row, headers, 'healthcare-related'),
      videoGames: getVal(row, headers, 'designing video games'),
      csCourseTaken: getVal(row, headers, 'Computer Science or IT course'),
      specificInterests: getVal(row, headers, "specific interests that weren't"),
      additionalQuestions: getVal(row, headers, 'additional questions'),
      isDuplicate: false,
      isNewest: true,
      adminNotes: '',
      status: 'pending',
    };
    
    interns.push(intern);
  }
  
  console.log(`\n=== PARSE SUMMARY ===`);
  console.log(`Total data rows processed: ${dataRows.length}`);
  console.log(`Successful interns parsed: ${interns.length}`);
  console.log(`Rows skipped - null/undefined: ${skippedRows}`);
  console.log(`Rows skipped - empty: ${shortRows}`);
  console.log(`Rows skipped - no names: ${emptyNameRows}`);
  console.log(`=== END SUMMARY ===\n`);
  
  return markDuplicates(interns);
}

function markDuplicates(interns: Intern[]): Intern[] {
  const groups = new Map<string, Intern[]>();
  
  for (const intern of interns) {
    const key = `${intern.firstName.toLowerCase()}_${intern.lastName.toLowerCase()}`;
    if (!groups.has(key)) groups.set(key, []);
    groups.get(key)!.push(intern);
  }
  
  for (const [, group] of groups) {
    if (group.length <= 1) continue;
    
    // Sort by timestamp descending (newest first)
    group.sort((a, b) => {
      const da = new Date(a.timestamp).getTime() || 0;
      const db = new Date(b.timestamp).getTime() || 0;
      return db - da;
    });
    
    // Newest is first, rest are older duplicates
    for (let i = 0; i < group.length; i++) {
      group[i].isDuplicate = true;
      group[i].isNewest = i === 0;
      if (i > 0) {
        group[i].duplicateOf = group[0].id;
      }
    }
  }
  
  return interns;
}
